Optum/dce

README.md
Link to readthedocs.io in Readme
=> Link to readthedocs.io in Readme

cmd/lambda/leases/list.go, cmd/lambda/leases/list_test.go, cmd/lambda/leases/main.go, go.mod, pipelines/pipeline.yml, tests/acceptance/api_test.go
- Download go modules to run tests
=> Download go mod items to be able to run functional tests

docs/index.rst
Fixed the broken index generation
=> Cleaned up broken index generation

tests/acceptance/usage_test.go
- Fix DB usage testing to handle pagination
=> Fix an issue with db usage testing not dealing with pagination

cmd/lambda/leases/delete_test.go, cmd/lambda/leases/main.go
=> general cleanup of unneeded stuff

modules/alarms_sns.tf, modules/artifacts_bucket.tf, modules/authentication/cognito.tf, modules/authentication/iam.tf, modules/cloudwatch_event/variables.tf, modules/email_identity.tf, modules/gateway.tf, modules/main.tf, modules/outputs.tf, pipelines/destroy-pr-env.yml, pipelines/pipeline.yml, scripts/install_ci.sh
- Update Terraform and TFLint Versions
=> Update TF and tflint versions

pkg/usage/usage.go
When filtering GET usage by start date it should return all records with startDate greater than or equal to input filter date
=> fix bug with start date

cmd/lambda/accounts/get.go, cmd/lambda/accounts/get_test.go, pkg/api/error.go, pkg/api/error_test.go, pkg/errors/error.go, pkg/errors/error_test.go, pkg/errors/stack.go
- New dceerr package for managing all errors going forward
- Allow for dynamic error printing in the API layer
Error wrapping still needs to be solved.  The database simplification work should complete this errors package.
api/response should eventually go away.  The models aren't needed and the response code will move to the api package.
=> New dceerr package for going forward error management

CHANGELOG.md
Preparing for release of v0.24.0
=> Update changelog for v0.24.0

pipelines/pipeline.yml, tests/acceptance/api_test.go
Our tagged release pipelines were not publishing file artifacts to Github:
https://dev.azure.com/OptumDCE/DCE/_build/results?buildId=1767&view=logs&j=72c04d33-7fe0-5dbb-c2b5-e1c36f5012d4&t=db71597a-64c0-5121-67c0-16e4df4b54bb
This fixes the pipeline to publish those file artifacts
See build for a `vTest_DELETE_ME` tag:
https://dev.azure.com/OptumDCE/DCE/_build/results?buildId=1790&view=logs&j=72c04d33-7fe0-5dbb-c2b5-e1c36f5012d4&t=db71597a-64c0-5121-67c0-16e4df4b54bb
..and the succesful release
https://github.com/Optum/dce/releases/tag/vTest_DELETE_ME
----
=> Pipeline: Fix missing Github release assets

cmd/lambda/update_principal_policy/main.go
- Add missing Regions to template processing
=> add regions to policy to fix an issue with rendering template

tests/acceptance/api_test.go, tests/acceptance/update_lease_status_test.go
Fix #136 
- Cleanup IAM roles and policies created for testing
=> cleanup iam roles and policies

tests/acceptance/api_test.go
Fix #228 
- Adjust message in functional tests based on day
=> Fix functional tests to adjust based on date

CHANGELOG.md, cmd/lambda/leases/get.go, cmd/lambda/leases/list_test.go, tests/acceptance/api_test.go
=> Don't 404 on accounts GET

CHANGELOG.md
=> Update CHANGELOG for v0.26.0

docs/howto.md
=> Added documentation for CLI changes.

CHANGELOG.md, cmd/lambda/leases/delete.go, cmd/lambda/leases/delete_test.go, cmd/lambda/leases/main.go, modules/swagger.yaml, pkg/db/db_test.go, tests/acceptance/api_test.go
fix #121 
- add the ability to delete leases by ID
=> allow for deleting a lease by ID

cmd/codebuild/reset/default-nuke-config-template.yml, cmd/codebuild/reset/main.go
- Switch the nuke template variable back to ID to help reduce breaking changes
=> switch the template structure back to ID to prevent breaking changes

modules/artifacts_bucket.tf, pipelines/pipeline.yml, scripts/create-tf-backend.sh, tests/acceptance/artifacts_bucket_test.go
Trying to run our PR DCE deployments inside a DCE child account.
**Driving this change:**
- Our PR account has a ton of orphaned resources, which costs $$, presents security risk, and hits AWS resource limits (causing failed builds)
- Dogfooding -- can we use DCE as we intend our customers to use it? testing out the dce-cli
**Overview of changes**
- Before TF deploy, new step to get access to a DCE child account
- Creates a lease for the PR, with `PrincipalID=github-pr-<pr#>`, or uses existing lease if already created
- "Logs in" to that lease, generating AWS creds for the DCE child account
- Those child creds are used in future TF deploy/functional-test steps.
**Also..**
- Remove access logging from our artifacts bucket. The number of objects this generates made nuking difficult, and …
=> DCEify PR accounts

cmd/lambda/accounts/update_test.go, pkg/account/model.go, pkg/account/service_test.go, pkg/account/validate.go, pkg/account/validate_test.go, pkg/arn/arn.go, pkg/arn/arn_test.go, pkg/data/account_test.go, pkg/data/accounts_test.go, pkg/data/helpers.go, pkg/data/helpers_test.go
-  Create a new arn type that makes working with ARNs easier
=> create a new arn type to make working with ARNs easier

CHANGELOG.md
=> Tag v0.27.0 in changelog

README.md, docs/concepts.md, docs/home.md
Adding product name trademark to prominent locations in the documentation, see legal guidelines:
"In written documents – it is only necessary to use a symbol with the first instance of the mark, or with the most prominent placement of the mark. It is a common misconception that each and every instance of the mark should bear a trademark symbol. Overuse creates visual clutter and may detract from the aesthetic appeal of the piece. Provided there is at least one conspicuous use of the TM, SM, or ® on the face of the writing, do not be afraid to eliminate superfluous markings."
=> Add trademark for product name 

cmd/lambda/publish_lease_events/main.go
- Revert back a change that was made to silently continue when the lease status changes to inactive and the lease event lambda was failing trying to change it.
=> silently continue when account status change fails

cmd/lambda/accounts/main.go, cmd/lambda/leases/main.go, pkg/config/servicebuild.go
- Move dependency work into configurator
=> move dependency work into configurator

pipelines/pipeline.yml
End our PR DCE lease during the cleanup stage, so we don't run out of accounts.
Run aws-nuke in dryrun mode for functional tests. This fixes an issue where aws-nuke would be triggered by functional tests, resulting in the `DCEPrincipal-nonprod` role being deleting. Future builds would then fail, because we couldn't login to our PR lease.
=> Pipeline: end lease on cleanup

cmd/lambda/accounts/update.go, cmd/lambda/accounts/update_test.go, cmd/lambda/accounts/validate.go, go.mod, go.sum, pkg/account/service.go
- Support updating nearly all fields with the account service update function
=> Support updating most fields in the account service update function

CHANGELOG.md, docs/iam-policies.md, go.mod, go.sum, modules/fixtures/policies/principal_policy.tmpl
Latest version of aws-nuke [supports deleting Athena resources](https://github.com/Optum/aws-nuke/pull/3),
so we can now let DCE principals use the service
=> Allow athena:*, upgrade aws-nuke to v1.1.0

cmd/lambda/leases/validate.go, cmd/lambda/update_lease_status/main_test.go, cmd/lambda/update_lease_status/spend.go, cmd/lambda/usage/get.go, cmd/lambda/usage/list.go, pkg/data/usage.go, pkg/data/usage_test.go, pkg/data/usages.go, pkg/data/usages_test.go, pkg/usage/model.go, pkg/usage/usage.go, pkg/usage/validate.go, pkg/usage/validate_test.go, tests/acceptance/api_test.go, tests/acceptance/update_lease_status_test.go, tests/acceptance/usage_test.go
- Add new data layer for usage
=> usage data layer

cmd/lambda/publish_lease_events/main.go, cmd/lambda/publish_lease_events/main_test.go
- Fix an issue when transitionaccountstatus fails and we don't get the account record.  Make a separate call to get the account so we know we have the correct record.
=> fix an issue with having the account record

pkg/usage/service_test.go
- Don't hard code dates in unit test
=> don't hardcode dates

cmd/lambda/update_principal_policy/main.go, cmd/lambda/update_principal_policy/main_test.go, pkg/account/accountiface/mocks/Servicer.go, pkg/account/accountiface/servicer.go, pkg/account/service.go, pkg/account/service_test.go, pkg/accountmanager/iam.go, pkg/accountmanager/iam_test.go, pkg/accountmanager/service.go
- Rework update principal policy function to utilize new account services
=> Rework update principal policy lambda to use new account services

CHANGELOG.md, docs/policies.md, modules/fixtures/policies/principal_policy.tmpl
Signed-off-by: Bill Schneider <bill.schneider@optum.com>
=> added tag:* to policy template

cmd/lambda/state_get_lease/main_test.go, cmd/lambda/state_get_lease_usage/main.go, cmd/lambda/state_get_lease_usage/main_test.go, pkg/accountmanager/service.go, pkg/accountmanager/service_test.go, pkg/accountmanager/usage.go, pkg/accountmanager/usage_test.go, pkg/data/dataiface/mocks/UsageLease.go, pkg/data/dataiface/usagelease.go, pkg/data/usagelease.go, pkg/data/usagelease_test.go, pkg/data/usageprincipal_test.go, pkg/usage/mocks/LeaseReaderWriter.go, pkg/usage/mocks/LeaseWriter.go, pkg/usage/service.go, pkg/usage/service_test.go, pkg/usage/usageiface/mocks/Servicer.go, pkg/usage/usageiface/servicer.go
- Move usage summing back into data layer.  Separate out lease and principal usage structs and data layers
=> move sum logic back into data layer

cmd/lambda/state_end_lease/main.go, cmd/lambda/state_end_lease/main_test.go, cmd/lambda/state_get_lease/main.go, modules/fixtures/state_machines/lease.json, modules/lease_usage_state_machine.tf
- End lease when time is reached
=> End Lease at end of lease

pkg/accountmanager/iam.go
- Fix an issue where Account manager was comparing pointers and not the actual values
=> Compare the value not the pointers

pkg/accountmanager/iam.go
Add account details to update principal policy log messages## Types of changes
=> Add account info to update principal policy log messages

CHANGELOG.md, docs/iam-policies.md, docs/policies.md, modules/fixtures/policies/principal_policy.tmpl
Missing permission to application-autoscaling:*, needed to make autoscaling fully work
=> added application-autoscaling:*

README.md
improved readability and DCE purpose
=> update product introduction

scripts/migrations/v0.30.1_db_update_AccountStatus_field/main.go
script to cleanup accounts pool. This script will update selected accounts to status "DeleteReady".
=> script to cleanup accounts pool

pipelines/pipeline.yml, scripts/install_ci.sh
- Upgrade version of dce-cli in pipeline to [v0.5.0](https://github.com/Optum/dce-cli/blob/master/CHANGELOG.md#v050)
- Includes some usability updates, that simplify our pipeline code
https://github.com/Optum/dce-cli/blob/master/CHANGELOG.md#v050
=> Upgrade dce-cli in pipeline to v0.5.0

CHANGELOG.md
=> DCE Release v0.31.0

cmd/lambda/update_lease_status/main_test.go, cmd/lambda/update_lease_status/spend.go, pkg/usage/usage.go
Bug fix: Wrong date printed when lease started and spend calculated are on the same day.
#350
=> Bug fix: Wrong date printed when lease started and spend calculated are on the same day. #350

CHANGELOG.md
=> release v0.31.2

CHANGELOG.md
Based of PR https://github.com/Optum/dce/pull/362
=> release v0.31.3

CHANGELOG.md, docs/iam-policies.md, modules/fixtures/policies/principal_policy.tmpl
Add `iotanalytics:*` to principal IAM policy
=> Add 'iotanalytics:*' to principal IAM policy.

CHANGELOG.md, go.mod, go.sum
=> Upgrade aws-nuke to v1.3.0

CHANGELOG.md, cmd/lambda/accounts/list_test.go, cmd/lambda/fan_out_update_lease_status/main.go, cmd/lambda/populate_reset_queue/main.go, cmd/lambda/populate_reset_queue/main_test.go, go.mod, go.sum, pkg/account/model.go, pkg/data/accounts.go, pkg/data/accounts_test.go, scripts/migrations/v0.21.0_rename_db_tables_dce/main.go
- Fix populate reset queue when dynamodb returns paginated result
- Add account status to last evaluated key when querying account table using global secondary index
- Fix gos
ec issue related to G601 (CWE-118): Implicit memory aliasing in for loop
=> Fix account pagination and its api functional test

CHANGELOG.md, modules/fixtures/policies/principal_policy.tmpl, modules/main.tf
Update aws provider ver and IAM policy
=> Update aws provider ver and IAM policy

CHANGELOG.md, modules/dynamodb.tf, pkg/data/leases.go
=> fix:get aws leases in order

CHANGELOG.md, pipelines/pipeline.yml, scripts/deploy.sh
Remove double quotes and extra characters on inputs passed to `deploy.sh` script in pipeline. Currently the values being passed to this script in the pipeline are coming from terraform outputs using the `terraform output` command. This can cause additional double quotes and a new line character to be added to the result (depending on the version of terraform) and can cause the script to fail. Example below:
Current output being interpolated to build S3 path:
`s3://"0123456789-dce-artifacts-cd"/lambda/account_pool_metrics.zip`
Error:
```bash
Invalid bucket name ""0123456789-dce-artifacts-cd"": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex...
```
New output (Valid S3 bucket path): 
`s3://0123456789-dce-artifacts-cd/lambda/account_pool_metrics.zip …
=> fix: remove extra characters on inputs passed to deployment script in pipeline

CHANGELOG.md, modules/fixtures/policies/principal_policy.tmpl
=> feat: add AWS Backup MountCapsule permission

CHANGELOG.md
Update release version in CHANGELOG manually prior to creating release `v0.33.9`
Going forward, leveraging a tool like [release-please](https://github.com/googleapis/release-please) to automate the CHANGELOG updates and version bumping should be explored.
=> chore: Update CHANGELOG for release v0.33.9

CHANGELOG.md
Update release version in CHANGELOG manually prior to creating release v0.34.0
=> chore: Update CHANGELOG for release v0.34.0

CHANGELOG.md, modules/main.tf
Fix Tf formatting issue introduced in #467
=> TF formatting

go.mod, pipelines/pipeline.yml
=> Update go version

CHANGELOG.md, go.mod, go.sum
=> update nuke version

CHANGELOG.md, cmd/lambda/populate_reset_queue/main.go, go.mod, go.sum
- Update Optum fork of the aws-nuke to use latest
- Add some minor logs to the reset queue lambda
=> Update optum aws-nuke with opensource

.gitignore, CHANGELOG.md, modules/main.tf, pipelines/destroy-pr-env.yml, pipelines/pipeline.yml
- Use latest terraform in Azure pipeline
- pin earliest allowed as 0.13.7
=> Upgrade terraform in pipeline, allow greater than 0.13.7 for user

go.mod, go.sum, modules/fixtures/policies/principal_policy.tmpl
- Deny DCE users from editing KMS policy, which very often can lead to unrecoverable keys via the nuke process
- Deny DCE users from creating support tickets
=> Deny DCE from support, deny DCE from editing KMS policies

docs/requirements.txt, go.mod, go.sum, modules/fixtures/policies/principal_policy.tmpl
Revert kms policy
- https://github.com/Optum/dce/pull/493
- https://github.com/Optum/dce/pull/498
- https://github.com/Optum/dce/pull/495
- https://github.com/Optum/dce/pull/496
- https://github.com/Optum/dce/pull/499
- https://github.com/Optum/dce/pull/497
=> Revert kms policy, package updates

CHANGELOG.md
=> Update changelog with latest changes due to nuke update

CHANGELOG.md, modules/fixtures/policies/principal_policy.tmpl
The PR has changes to deny the Amazon Bedrock service from DCE AWS accounts.
=> Block awsbedrock

.github/workflows/pipeline.yaml
=> Fix release step
